version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodeapp_container
    volumes:
      - ./:/souce
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${WEBSERVER_PORT}:3000"
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"

  # db_testing:
  #   image: mariadb:10.4
  #   restart: always
  #   volumes:
  #     - ./data/dbtest:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     MYSQL_DATABASE: "${DB_NAME}"
  #     MYSQL_USER: "${DB_USER}"
  #     MYSQL_PASSWORD: "${DB_PASSWORD}"
  #   ports:
  #     - "${DB_PORT_TESTING}:3306"
